### ISSUE TITLE
tpa plugin does not support MCDR1.x

### ISSUE THREAD

**Issue by fbano-0619** [Da-Dog/MCDR-Plugins#2]

**Comment by Da-Dog** [comment]
Hi, Can you copy and paste the error message here, I've made some changes to the plugin, if you don't mind, test and see if it works. Thank you

**Comment by fbano-0619** [comment]
Oh, I fix the problem by myself. I think you should also change line 3: utils.rtext to mcdreforged.api.rtext, or it will report no module named "utils.rtext" Fallen changed the naming in MCDR 1.X

**Comment by fbano-0619** [comment]
Oh, I fix the problem by myself. I think you should also change line 3: utils.rtext to mcdreforged.api.rtext, or it will report no module named "utils.rtext" Fallen changed the naming in MCDR 1.X
