### ISSUE TITLE
tps插件不会输出tps信息

### ISSUE THREAD

**Issue by Wings-Fantasy** [Da-Dog/MCDR-Plugins#3]
游戏内输入!!tps之后没有任何回应，控制台能看到输出了两行信息

**Comment by Community-Improvement-Service** [comment]
可以将信息粘贴上来吗，谢谢

**Comment by Da-Dog** [comment]
可以将信息粘贴上来吗，谢谢

**Comment by Wings-Fantasy** [comment]
<img src="https://s3.jpg.cm/2021/08/06/IAs12H.png" alt="服务器后台截图" border="0">
其中，!!tps help确实在游戏内输出了帮助信息<br>
!!qb是另一个插件的，不要在意

**Comment by Da-Dog** [comment]
已修复 043b968f11ca7ae9ebb3a4aa99c9db740c2d6a71 谢谢您指出的问题，Issue已关闭，需要的话可以重新打开
