### ISSUE TITLE
一个未经验证的疑问

### ISSUE THREAD

**Issue by Wings-Fantasy** [Da-Dog/MCDR-Plugins#4]
https://github.com/Da-Dog/MCDR-Plugins/blob/043b968f11ca7ae9ebb3a4aa99c9db740c2d6a71/MCDR-TPS/tps.py#L24-L27
在没有对外来输入值做任何处理的情况下直接使用，如果输入是`!!tps aaa`会不会导致插件崩溃？

**Comment by Da-Dog** [comment]
后台会报错但不会因为这个错误影响服务器或MCDR，做了一点修改变得更加人性化 d8bf15c2bc86864e1dd01fb8c15adfa1c530385d

**Comment by Wings-Fantasy** [comment]
这次修改我认为并不好，还是以`!!tps aaa`输入举例
https://github.com/Da-Dog/MCDR-Plugins/blob/d8bf15c2bc86864e1dd01fb8c15adfa1c530385d/MCDR-TPS/tps.py#L25
会产生一个错误，并且被except捕获
https://github.com/Da-Dog/MCDR-Plugins/blob/d8bf15c2bc86864e1dd01fb8c15adfa1c530385d/MCDR-TPS/tps.py#L27
输出提示信息之后，程序会继续执行
https://github.com/Da-Dog/MCDR-Plugins/blob/d8bf15c2bc86864e1dd01fb8c15adfa1c530385d/MCDR-TPS/tps.py#L28-L30
预计会在第29行再次产生错误，因为变量`time`未定义

建议改为：
```
                try:
                    time = int(args[1])
                    server.execute('debug start')
                    sleep(time)
                    server.execute('debug stop')
                except:
                    server.tell(info.player, "------ §c请输入整数 §f------")
```

另外可以考虑一下使用MCDR提供的指令树，使用参数节点避免这种问题

**Comment by Da-Dog** [comment]
对，我后来想到了这个问题（一开始测试没看控制台XD），又做了一下修改 1dccf8c8469d19c912b70c418b9a647df28b18a6

**Comment by Wings-Fantasy** [comment]
https://github.com/Da-Dog/MCDR-Plugins/blob/1dccf8c8469d19c912b70c418b9a647df28b18a6/MCDR-TPS/tps.py#L24-L31
我有点忘了Python变量的作用域了，在try里定义的变量，作用域是try还是整个def？

**Comment by Da-Dog** [comment]
整个def

**Comment by Wings-Fantasy** [comment]
没有其他问题了，这个issues我就关闭了
